#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx lint-staged

npm run build-via-theme
git add packages/es-components-via-theme/index.d.ts

npm run build-wtw-theme
git add packages/es-components-wtw-theme/index.d.ts

npm run build-wtw-legacy-theme
git add packages/es-components-wtw-legacy-theme/index.d.ts
