name: Deploy a Canary Build
on:
  workflow_dispatch:
    branches-ignore:
      - main
jobs:
  deploy_canary:
    name: Build And Deploy Canary Release
    runs-on: ubuntu-latest
    environment: canary
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PIPELINE_BOT_PAT }}
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - name: Install Dependencies
        run: |
          npm ci
      - name: Set Commitbot Identity
        run: |
          git config user.name "ES-Components Lerna Publish Bot"
          git config user.email "es-components-bot@wtw.org"
      - name: Lerna Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc
          npx lerna publish \
            --canary \
            --preid "$(git rev-parse --short HEAD)" \
            --conventional-commits \
            --changelog-preset conventional-changelog-eslint \
            --yes
