name: Cypress CI
on:
  pull_request_target:
    types: [opened, reopened, synchronize, closed]
  workflow_dispatch:
env:
  ES_COMPONENTS_DIR: packages/es-components

jobs:
  run-cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PIPELINE_BOT_PAT }}
          ref: ${{ github.head_ref || github.ref }}

      - name: NPM Clean Install
        run: |
          npm ci --workspaces --include-workspace-root # runs installs and builds themes

      - name: Setup Cypress
        working-directory: ${{ env.ES_COMPONENTS_DIR }}
        run: |
          npx cypress install
          npm start &
          npm run wait-for-start

      - name: Generate Cypress Config
        working-directory: ${{ env.ES_COMPONENTS_DIR }}
        run: |
          echo "$( \
            jq -s '.[0] * .[1]' cypress.json cypress-ci.json \
          )" > cypress-ci.json

      - uses: cypress-io/github-action@v5
        with:
          working-directory: ${{ env.ES_COMPONENTS_DIR }}
          config-file: cypress-ci.json
          install: false

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: ${{ env.ES_COMPONENTS_DIR }}/cypress/screenshots

      - run: npm run cypressreport
        working-directory: ${{ env.ES_COMPONENTS_DIR }}

      - name: Create Status check based on merged cypress results
        if: always()
        id: process-cypress
        uses: im-open/process-cypress-test-results@v2.0.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          results-file: ${{ env.ES_COMPONENTS_DIR }}/raw-results.json
          report-name: "Cypress ${{ github.run_number }}"
          create-status-check: true
          create-pr-comment: true
          update-comment-if-one-exists: true
          ignore-test-failures: false
          timezone: "america/denver"
